### ISSUE TITLE
Problems with IdeoViz

### ISSUE THREAD

**Issue by s-weissbach** [dridk/snp_location#1]
Everything works fine till:
`
ideo <- getIdeo("hg19")`
Which leads to the error:
`Error in `genome<-`(`*tmp*`, value = "hg19") : 
  Failed to set session genome to 'hg19'`
Do you have any idea how to fix this?

**Comment by dridk** [comment]
no idea :( 
You may check official doc to see if something has change
https://www.bioconductor.org/packages/3.7/bioc/vignettes/IdeoViz/inst/doc/Vignette.pdf

**Comment by s-weissbach** [comment]
Funny thing:
`ideo<-getIdeo("hg38")`
works fine. If i find the answer I'll comment here.

**Comment by s-weissbach** [comment]
Solution is quite easy to update rtracklayer & R to the newest version.
